### ISSUE TITLE
The container app will be in "Failed" status after executing "Edit Secret Value..." action for the default generated secret

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurecontainerapps#733] opened 2024-08-29 10:26 UTC
**OS:** All
**Build Version:** v0.7.1-alpha.0
**Regression:** Not a Regression

**Repro Steps:**
1. Open a [containerapps-albumapi-javascript](https://github.com/azure-samples/containerapps-albumapi-javascript) project in VS Code.
2. Right click one container apps environment -> Select "Create Container App from Workspace..." to create a container app.
3. Navigate to the "Secrets" node and execute "Edit Secret Value..." action for the default generated secret, the below error occurs.
![image](https://github.com/user-attachments/assets/e9127c33-f787-458e-9fd3-ef132facca0e)
4.  Refresh the Azure view.
5. Check whether the above container app is not in "Failed" status.

**Expect:**
The above container app is not in "Failed" status.

**Actual:**
The above container app is in "Failed" status.
![image](https://github.com/user-attachments/assets/a84cfc29-653b-4e06-89b5-80a1a207ef1a)

**More Info:**
1. Fail to execute some commands for the "Failed" container app with the same error of step 3, such as "Choose Revision Mode/Disable Ingress for Container App...". 
2. This issue will be fixed after creating a new secret.

**Comment by MicroFish91** [comment] 2024-09-03 18:52
Hmm, I think this one may be by-design.  The ACA service isn't letting you change the key because it's crucial for maintaining the registry configuration that we have set up.  When you change it, it appears to try and verify that the connection is still valid since it's set up in our registry configuration settings.

I wonder if it's worth trying to improve the error message here.... I'll bring this one up in triage.

**Comment by MicroFish91** [comment] 2024-09-04 18:21
Closing as by design

**Closed** 2024-09-13 17:00 UTC
Labels: AT-CTI
