### ISSUE TITLE
The "Inactive" revision is changed to "Active" after changing the revision mode twice

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurecontainerapps#550] opened 2023-11-01 10:18 UTC
**OS:** Win 10
**Build Version:** 20231101.3

**Repro Steps:**

1. Create a container app.
2. Change the revision mode to "Multiple" for the above container app.
3. Right click the revision and "Deactivate" it.
4. Change the revision mode to "Single".
5. Change the revision mode to "Multiple" again.
6. Check whether the revision is still "Inactive" or not.

**Expect:**
The revision is still "Inactive".
![image](https://github.com/microsoft/vscode-azurecontainerapps/assets/45614674/c8d225a0-02ef-45eb-9d26-f1e605cd0042)

**Actual:**
The revision is changed to "Active".
![image](https://github.com/microsoft/vscode-azurecontainerapps/assets/45614674/cd62d428-ee8f-43f9-b1b3-6678f3b19127)

**Comment by MicroFish91** [comment] 2023-11-22 18:40
Likely swapping to single revision mode is activating the revision, and then this is persisting when swapped back to multiple revisions mode.  Closing as by design.

**Closed by MicroFish91** 2023-11-22 18:40 UTC
Labels: AT-CTI
