### ISSUE TITLE
Only oldest tag showing when selecting image from Azure Container Registry

### ISSUE THREAD

**Issue by dlmutart** [microsoft/vscode-azurecontainerapps#131] opened 2022-06-01 15:03 UTC
When using the extension version 0.1.1 to Create Container App or Update Image in Container App, only the first or oldest tag from an existing ACR is available for selection in the drop down.   We have several versions of our docker image, with tags ch1, ch2, ..., ch8 in an ACR repository.  When performing the Create Container App for new app, or Update Image in Container App for existing app, and then picking the repository in existing Azure Container Registry, only the oldest tag ch1 is available for selection.   ch2 through ch8 aren't available in the drop-down.  Checking ACR via portal or command line, we can see all of these versions and tags are as expected in ACR.  It seems that the extension is not pulling in all of the available tags from ACR.

![Update Image Screenshot 2022-06-01 103958](https://user-images.githubusercontent.com/49531500/171436317-09c1621a-3916-4830-8b52-15737fe3f1c0.png)
![Create Container App Screenshot 2022-06-01 104016](https://user-images.githubusercontent.com/49531500/171436321-b869106e-0e56-45ab-ad93-4bff6d0627e6.png)

**Comment by nturinski** [comment] 2022-07-06 04:02
Thanks for filing this. I believe that this PR #137 should have resolved this! This should be out in the wild soon, so hopefully that unblocks you.

**Comment by nturinski** [comment] 2022-07-14 20:49
@dlmutart Could you verify if this has been fixed for you?  We released a new version last Thursday!

**Comment by nturinski** [comment] 2022-07-26 17:40
I'm going to go ahead and close this. If the issue is persisting, please re-open!

**Closed by nturinski** 2022-07-26 17:40 UTC
