### ISSUE TITLE
Only the "maxReplicase" property shows in the opened Scaling.json file

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurecontainerapps#84] opened 2022-04-06 12:03 UTC
**OS:** All
**Build Version:** 20220405.6
**Regression:** Not a regression

**Repro Steps:**
1. Expand one container app -> Right click "Scaling" node -> Select "View Properties".
2. Check whether all properties show in the opened Scaling.json file or not.

**Expect:**
All properties show in the opened Scaling.json file.
![image](https://user-images.githubusercontent.com/45614674/161970213-febe0c0a-22e8-4c94-830e-d6ad9fcf9180.png)

**Actual:**
Only the "maxReplicase" property shows in the opened Scaling.json file.
![image](https://user-images.githubusercontent.com/45614674/161970238-93bf5d43-62ab-4cff-b9de-4e240fb7eb02.png)

**Comment by nturinski** [comment] 2022-04-07 02:56
Thanks for paying attention to this, but this is intended behavior. When the minReplica isn't specified, we just display it at the minimum value possible which is 0.

I'll close this as by-design.

**Closed by nturinski** 2022-04-07 02:56 UTC
Labels: AT-CTI
