### ISSUE TITLE
[Suggestion] It would be better to add the "Revision" to the "Restart" action in the context menu

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurecontainerapps#526] opened 2023-10-30 07:52 UTC
**OS:** All
**Build Version:** 20231027.2

**Repro Steps:**
1. Create a container apps environment -> Create a container app.
2. Right click the container app.
3. Check the context menu.

**Actual:**
1. There is a "Restart" action in the context menu.
    <img width="353" alt="Screenshot 2023-10-30 at 15 08 17" src="https://github.com/microsoft/vscode-azurecontainerapps/assets/57662131/42809e3d-3a63-4cf5-916e-edf5a0786db6">
2. It is confusing that the "Restart" action works for the container app or the revision.

**Suggestion:**
It would be better to add the "Revision" to the "Restart" action in the context menu.

**Comment by MicroFish91** [comment] 2023-11-22 18:47
Closing as by design because we are trying to hide the concept of revisions to our users since most people only use single revision mode anyway.

**Closed by MicroFish91** 2023-11-22 18:47 UTC
Labels: AT-CTI
